services:
  # Sleep Data Microservice
  sleep-service:
    image: ghcr.io/volkerfelix/sleep-data-microservice:sha-58f5177@sha256:6eb03f7a6e1d4449d8f7c4c1513a34f534ffdbb13c02935852f715d50b7294cf
    ports:
      - "8001:8001"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/sleep_data
      - LOG_LEVEL=INFO
      - DEBUG=False
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sleep-network

  # Visualization Application
  sleep-visu:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - SLEEP_API_BASE_URL=http://sleep-service:8001/api
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - sleep-service
    networks:
      - sleep-network

  # PostgreSQL Database for Sleep Data Microservice
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sleep_data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sleep-network

  # Optional: PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sleepdata.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
    networks:
      - sleep-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  sleep-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data: